### ISSUE TITLE
Add basic C++ Program

### ISSUE THREAD

**Issue by cyberpvn7** [Pavan-Kamthane/Cpp_Lang#1]
Create a folder of your name 
then add you code

### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

**Comment by Abhinav092003** [comment]
@Pavan-Kamthane please 🙏 assign me i will uploads c++ program...i know c,c++ and Java very well...ease assign me

**Comment by cyberpvn7** [comment]
U can PR directly

**Comment by Debayan97531** [comment]
@Pavan-Kamthane I have added the pr.Will you kindly merge it??

**Comment by Debayan97531** [comment]
#27

**Comment by shreyapd666** [comment]
merge my code please

**Comment by arnav-vivian** [comment]
binar tree node deletion code please merge it.

**Comment by bristi07** [comment]
Bubble sort code .please merge it

**Comment by jyotika6221** [comment]
Please assign me the issue.

**Comment by apoorvatiwaree** [comment]
I would like to contribute. Please assign the issue to me

**Comment by cyberpvn7** [comment]
@apoorvatiwaree u can pr directly
