### ISSUE TITLE
File ---> file named folder 

### ISSUE THREAD

**Issue by cyberpvn7** [Pavan-Kamthane/Cpp_Lang#61]
Hey guys I have one task for you.

In this repository those files which are not in folder_**(except readme.md and contribution.md)**_ , put them in folder of same filed name.
**And if they are already in folder then don't touch them.**

Example if someone added **helloworld**_program then you have to create a helloworld named folder then add this **helloworld** file, that set.

I think it is enough to explain.

Thanks.

**Comment by deveshpandee** [comment]
Please assign me this issue.

**Comment by Jyotisaini-2001** [comment]
Hii, I am interested to contribute in this issue.
Please assign me this issue @Pavan-Kamthane 
thank you!!
